---
title: "Separate ping time"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(data.table, lubridate, geosphere, magrittr)
setDTthreads(parallel::detectCores())
df = fread("data/20190626_ping_with_weather.csv") 
```

# Solution 3

```{r}
ping_df = d %>% 
  .[,`:=`(driver1 = gsub("\"", "", driver1),
          DATIME  = ymd_hms(DATIME))] %>% 
  setkey(driver1, DATIME) %>% 
  .[, .(ping_id, trip_id, driver = driver1, ping_time = DATIME, 
        lon = LONGITUDE, lat = LATITUDE, speed = SPEED,
        PRECIP_INTENSITY, PRECIP_PROBABILITY, WIND_SPEED, 
        VISIBILITY, SUNRISE_TIME, SUNSET_TIME)]
```

```{r}
trip_df = ping_df %>% 
  .[, .SD[c(1, .N)], by = c("driver", "trip_id")] %>% 
  .[,time_type := rep(c("start_time", "end_time0"), .N/2)] %>% 
  .[,time_type := factor(time_type, levels = c("start_time", "end_time0"))] %>% 
  dcast(driver + trip_id ~ time_type, value.var = "ping_time") %>% 
  .[,trip_time := as.integer(difftime(end_time0, start_time, units = "mins"))] %>% 
  .[,trip_units := ceiling(trip_time/30)] %>% 
  .[rep(seq(.N), trip_units), !c("trip_time", "trip_units")] %>% 
  .[,add1 := 0:(.N-1), by = c("driver", "trip_id")] %>% 
  .[,start_time := start_time[1] + add1*30*60, .(driver, trip_id)] %>% 
  .[,end_time := shift(start_time, type = "lead"), .(driver, trip_id)] %>% 
  .[,end_time := {end_time[.N] = end_time0[.N]; end_time}, .(driver, trip_id)] %>% 
  .[,c("end_time0", "add1") := NULL] %>% 
  .[, trip_time := as.integer(difftime(end_time, start_time, units = "mins"))] %>% 
  setkey(driver, start_time, end_time) %>% 
  .[, new_trip_id := .I] %>% 
  .[, .(new_trip_id, driver, start_time, end_time, trip_time)]
```

```{r}
# overlap ping and new trips
pitr_df = ping_df %>% 
  .[,dummy := ping_time] %>% 
  setkey(driver, ping_time, dummy) %>% 
  foverlaps(trip_df, type = "within",
                    by.x = c("driver", "ping_time", "dummy"),
                    mult = "first", nomatch = NA) %>% 
  .[, dummy := NULL] %>% 
  .[,.(ping_id, driver, ping_time, trip_id, new_trip_id,
       start_time, end_time, trip_time, lon, lat, speed,
       PRECIP_INTENSITY, PRECIP_PROBABILITY, WIND_SPEED,
       VISIBILITY, SUNRISE_TIME, SUNSET_TIME)]

ovlap_tripid = pitr_df[, .N, new_trip_id][,N := NULL]
unmat_trip = trip_df[!ovlap_tripid, on = "new_trip_id"]
```

```{r}
# distance
dist = pitr_df %>% 
  .[,.(driver, trip_id, ping_id, lon, lat)] %>% 
  .[,`:=`(lon1 = shift(lon, type = "lag", fill = NA),
          lat1 = shift(lat, type = "lag", fill = NA)), 
    by = c("driver", "trip_id")] %>% 
  .[,distance := distHaversine(cbind(lon, lat), cbind(lon1, lat1))] %>% 
  .[,distance := round(distance/1609.344, 3)] %>% 
  .[,.(ping_id, distance)] %>% 
  setkey(ping_id)
```

```{r}
# merge distance back to ping dat and add unmatched trips
newtrip = dist %>% 
  .[pitr_df, on = "ping_id"] %>% 
  .[,.(start_time = start_time[1], end_time = end_time[1],
       trip_time = trip_time[1], mh_trip_id = trip_id[1],
       distance = sum(distance, na.rm = TRUE),
       start_lat = lat[1], start_lon = lon[1],
       end_lat = lat[.N], end_lon = lon[.N],
       ave_ping_speed = mean(speed, na.rm = TRUE),
       PRECIP_INTENSITY = mean(PRECIP_INTENSITY, na.rm = TRUE),
       PRECIP_PROBABILITY = mean(PRECIP_PROBABILITY, na.rm = TRUE),
       WIND_SPEED = mean(WIND_SPEED, na.rm = TRUE),
       VISIBILITY = mean(VISIBILITY, na.rm = TRUE)),
    by = c("driver", "new_trip_id")] %>% 
  list(unmat_trip) %>% 
  rbindlist(fill = TRUE) %>% 
  setkey(driver, start_time)
```

```{r}
fwrite(newtrip, "gen_data/20190707new_trip_halfhour.csv")
```

# Critical events

## read CE

```{r}
# critical events
ce = fread("data/CRITICAL_EVENT_QUERY2016-09-30 10-58-28.csv") %>% 
  .[,`:=`(EMPLID = stringr::str_replace_all(EMPLID, " ", ""),
          EVT_TYP = stringr::str_replace_all(EVT_TYP, " ", ""))] %>%
  .[,event_time := ymd_hms(paste(EVENT_DATE, EVENT_HOUR, sep = " "))]

# driver information
alldr = fread("data/ALL_DRIVERS_DATA2016-09-30 10-53-42.csv") %>% 
  .[,EMPLID := stringr::str_replace_all(EMPLID, " ", "")]

# alpha to employee ID
alpha = fread("data/ALPHA_TO_EMPLID2016-10-21 14-00-24.csv") %>% 
  .[,driver := tolower(ALPHA)] %>% 
  .[,`:=`(driver = stringr::str_replace_all(driver, " ", ""),
          EMPLID = stringr::str_replace_all(EMPLID, " ", ""))] %>% 
  .[,.(driver, EMPLID)] %>% 
  setkey(driver)

d500 = newtrip %>% 
  .[,.N, driver] %>% 
  setkey(driver)

d = alpha %>% 
  .[d500, on = "driver"] %>% 
  setkey(EMPLID)# there are duplicated EMPLID

d2 = alldr %>% 
  .[d, on = "EMPLID"] %>% 
  .[,BIRTHDATE := ymd(BIRTHDATE)] %>% 
  .[!is.na(BIRTHDATE),] %>% 
  setkey(driver) %>% 
  .[,n_missing := rowSums(is.na(.))] %>% 
  .[order(driver, -n_missing)] %>% 
  .[,head(.SD, 1), by = driver] %>% 
  .[, age := 2015 - year(BIRTHDATE)] %>% 
  .[!(driver %in% c("kisi", "codc"))] %>% 
  .[,.(driver, EMPLID, age)]

ce0 = ce[EMPLID %in% d2[,EMPLID],]
ce0 = alpha[ce0, on = "EMPLID"] %>% 
  .[,.(driver, event_time, EVT_TYP)] %>% 
  .[,EVT_TYP := dplyr::recode(EVT_TYP, 
                              "HEADWAY" = "HW", 
                              "HARD_BRAKING" = "HB", 
                              "COLLISION_MITIGATION" = "CM", 
                              "ROLL_STABILITY" = "RS")] %>% 
  setkey(driver, event_time) %>% 
  unique()
# ce0[,diff := as.integer(difftime(event_time, shift(event_time, 1),
#                                     units = "mins")),EMPLID]
# ce0[,sum(diff <= 1, na.rm = TRUE)]
```

## Merge CE back to trips

```{r}
ce1 = ce0 %>% 
  .[,dummy := event_time] %>% 
  setkey(driver, event_time, dummy)

ce2merge = newtrip %>% 
  setkey(driver, start_time, end_time) %>% 
  foverlaps(ce1, mult = "all", type = "any", 
            by.x = c("driver", "start_time", "end_time")) %>% 
  .[, dummy := NULL] %>% 
  .[!is.na(EVT_TYP),] %>% 
  .[,.(new_trip_id, driver, event_time, EVT_TYP)] %>% 
  .[,.(CE_num = .N, 
       CE_time = paste(event_time, collapse = ";"),
       CE_type = paste(EVT_TYP, collapse = ";")), 
    new_trip_id]

newtrip_ce = ce2merge %>% 
  .[newtrip, on = 'new_trip_id'] %>% 
  .[,ave_dist_speed := distance*60/trip_time] %>% 
  .[,ave_dist_speed := ifelse(ave_dist_speed >= 80, 
                              ave_ping_speed, ave_dist_speed)] %>% 
  setkey(driver, start_time) %>% 
  merge(d2[,.(driver, age)], by = "driver", all.x = TRUE)
```

```{r}
fwrite(ce0, "gen_data/20190708CE500drivers.csv")
fwrite(newtrip_ce, "gen_data/20190708newtrip_ce.csv")
```


# A function

```{r}
rmk_trip = function(data = df, sep_time = 30, datapath = "data/"){
  # 01. clean the original data
  ping_df = df %>% 
    .[,`:=`(driver1 = gsub("\"", "", driver1),
            DATIME  = ymd_hms(DATIME))] %>% 
    setkey(driver1, DATIME) %>% 
    .[, .(ping_id, trip_id, driver = driver1, ping_time = DATIME, 
          lon = LONGITUDE, lat = LATITUDE, speed = SPEED,
          PRECIP_INTENSITY, PRECIP_PROBABILITY, WIND_SPEED, 
          VISIBILITY, SUNRISE_TIME, SUNSET_TIME)]
  
  # 02. trip_df
  trip_df = ping_df %>% 
    .[, .SD[c(1, .N)], by = c("driver", "trip_id")] %>% 
    .[,time_type := rep(c("start_time", "end_time0"), .N/2)] %>% 
    .[,time_type := factor(time_type, levels = c("start_time", "end_time0"))] %>% 
    dcast(driver + trip_id ~ time_type, value.var = "ping_time") %>% 
    .[,trip_time := as.integer(difftime(end_time0, start_time, units = "mins"))] %>% 
    .[,trip_units := ceiling(trip_time/sep_time)] %>% 
    .[rep(seq(.N), trip_units), !c("trip_time", "trip_units")] %>% 
    .[,add1 := 0:(.N-1), by = c("driver", "trip_id")] %>% 
    .[,start_time := start_time[1] + add1*sep_time*60, .(driver, trip_id)] %>% 
    .[,end_time := shift(start_time, type = "lead"), .(driver, trip_id)] %>% 
    .[,end_time := {end_time[.N] = end_time0[.N]; end_time}, .(driver, trip_id)] %>% 
    .[,c("end_time0", "add1") := NULL] %>% 
    .[, trip_time := as.integer(difftime(end_time, start_time, units = "mins"))] %>% 
    setkey(driver, start_time, end_time) %>% 
    .[, new_trip_id := .I] %>% 
    .[, .(new_trip_id, driver, start_time, end_time, trip_time)]
  
  # 03. overlap ping and new trips
  pitr_df = ping_df %>% 
    .[,dummy := ping_time] %>% 
    setkey(driver, ping_time, dummy) %>% 
    foverlaps(trip_df, type = "within",
              by.x = c("driver", "ping_time", "dummy"),
              mult = "first", nomatch = NA) %>% 
    .[, dummy := NULL] %>% 
    .[,.(ping_id, driver, ping_time, trip_id, new_trip_id,
         start_time, end_time, trip_time, lon, lat, speed,
         PRECIP_INTENSITY, PRECIP_PROBABILITY, WIND_SPEED,
         VISIBILITY, SUNRISE_TIME, SUNSET_TIME)]
  
  ovlap_tripid = pitr_df[, .N, new_trip_id][,N := NULL]
  unmat_trip = trip_df[!ovlap_tripid, on = "new_trip_id"]
  
  # 04. distance
  dist = pitr_df %>% 
    .[,.(driver, trip_id, ping_id, lon, lat)] %>% 
    .[,`:=`(lon1 = shift(lon, type = "lag", fill = NA),
            lat1 = shift(lat, type = "lag", fill = NA)), 
      by = c("driver", "trip_id")] %>% 
    .[,distance := distHaversine(cbind(lon, lat), cbind(lon1, lat1))] %>% 
    .[,distance := round(distance/1609.344, 3)] %>% 
    .[,.(ping_id, distance)] %>% 
    setkey(ping_id)
  
  # 05. merge distance back to ping dat and add unmatched trips
  newtrip = dist %>% 
    .[pitr_df, on = "ping_id"] %>% 
    .[,.(start_time = start_time[1], end_time = end_time[1],
         trip_time = trip_time[1], mh_trip_id = trip_id[1],
         distance = sum(distance, na.rm = TRUE),
         start_lat = lat[1], start_lon = lon[1],
         end_lat = lat[.N], end_lon = lon[.N],
         ave_ping_speed = mean(speed, na.rm = TRUE),
         PRECIP_INTENSITY = mean(PRECIP_INTENSITY, na.rm = TRUE),
         PRECIP_PROBABILITY = mean(PRECIP_PROBABILITY, na.rm = TRUE),
         WIND_SPEED = mean(WIND_SPEED, na.rm = TRUE),
         VISIBILITY = mean(VISIBILITY, na.rm = TRUE)),
      by = c("driver", "new_trip_id")] %>% 
    list(unmat_trip) %>% 
    rbindlist(fill = TRUE) %>% 
    setkey(driver, start_time)
  
  # 06. Critical Events
  # 06a. critical events table
  ce = fread(paste0(datapath, "CRITICAL_EVENT_QUERY2016-09-30 10-58-28.csv")) %>% 
    .[,`:=`(EMPLID = stringr::str_replace_all(EMPLID, " ", ""),
            EVT_TYP = stringr::str_replace_all(EVT_TYP, " ", ""))] %>%
    .[,event_time := ymd_hms(paste(EVENT_DATE, EVENT_HOUR, sep = " "))]
  # 06b. driver information
  alldr = fread(paste0(datapath, "ALL_DRIVERS_DATA2016-09-30 10-53-42.csv")) %>% 
    .[,EMPLID := stringr::str_replace_all(EMPLID, " ", "")]
  # 06c. alpha to employee ID
  alpha = fread(paste0(datapath, "ALPHA_TO_EMPLID2016-10-21 14-00-24.csv")) %>% 
    .[,driver := tolower(ALPHA)] %>% 
    .[,`:=`(driver = stringr::str_replace_all(driver, " ", ""),
            EMPLID = stringr::str_replace_all(EMPLID, " ", ""))] %>% 
    .[,.(driver, EMPLID)] %>% 
    setkey(driver)
  
  d500 = newtrip %>% 
    .[,.N, driver] %>% 
    setkey(driver)
  
  d = alpha %>% 
    .[d500, on = "driver"] %>% 
    setkey(EMPLID)# there are duplicated EMPLID
  
  d2 = alldr %>% 
    .[d, on = "EMPLID"] %>% 
    .[,BIRTHDATE := ymd(BIRTHDATE)] %>% 
    .[!is.na(BIRTHDATE),] %>% 
    setkey(driver) %>% 
    .[,n_missing := rowSums(is.na(.))] %>% 
    .[order(driver, -n_missing)] %>% 
    .[,head(.SD, 1), by = driver] %>% 
    .[, age := 2015 - year(BIRTHDATE)] %>% 
    .[!(driver %in% c("kisi", "codc"))] %>% 
    .[,.(driver, EMPLID, age)]
  
  ce0 = ce[EMPLID %in% d2[,EMPLID],]
  ce0 = alpha[ce0, on = "EMPLID"] %>% 
    .[,.(driver, event_time, EVT_TYP)] %>% 
    .[,EVT_TYP := dplyr::recode(EVT_TYP, 
                                "HEADWAY" = "HW", 
                                "HARD_BRAKING" = "HB", 
                                "COLLISION_MITIGATION" = "CM", 
                                "ROLL_STABILITY" = "RS")] %>% 
    setkey(driver, event_time) %>% 
    unique()
  
  # 07. Merge CE back to trips
  ce0 %>% 
    .[,dummy := event_time] %>% 
    setkey(driver, event_time, dummy)
  
  ce2merge = newtrip %>% 
    setkey(driver, start_time, end_time) %>% 
    foverlaps(ce0, mult = "all", type = "any", 
              by.x = c("driver", "start_time", "end_time")) %>% 
    .[, dummy := NULL] %>% 
    .[!is.na(EVT_TYP),] %>% 
    .[,.(new_trip_id, driver, event_time, EVT_TYP)] 
  
  newtrip_ce = ce2merge %>% 
    .[,.(CE_num = .N, 
         CE_time = paste(event_time, collapse = ";"),
         CE_type = paste(EVT_TYP, collapse = ";")), 
      new_trip_id] %>% 
    .[newtrip, on = 'new_trip_id'] %>% 
    .[,ave_dist_speed := distance*60/trip_time] %>% 
    .[,ave_dist_speed := ifelse(ave_dist_speed >= 80, 
                                ave_ping_speed, ave_dist_speed)] %>% 
    setkey(driver, start_time) %>% 
    merge(d2[,.(driver, age)], by = "driver", all.x = TRUE)
  
  return(list(trip_has_CE = newtrip_ce, 
              CE_alone    = ce2merge))
}
```

```{r}
zz = rmk_trip()
```

```{r}
fwrite(zz$CE_alone, paste0("gen_data/", today(), "_nt_CE_alone.csv"))
fwrite(zz$trip_has_CE, paste0("gen_data/", today(), "_nt_trip_has_CE.csv"))
```







































# Solution 1

```{r}
# ping_df[,diff := as.integer(difftime(ping_time, shift(ping_time, 1),
#                                      units = "mins")),
#         by = c("driver", "trip_id")]
# ping_df[, diff := {diff[1] = 0L; diff}, c("driver", "trip_id")]
# ping_df[,cum_mins := cumsum(diff), c("driver", "trip_id")]
# ping_df[,cum_halfhour := round(cum_mins/30, 3), driver]
# ping_df[,flag0 := floor(round(cum_mins/30, 3)), driver]
# 
# t1 = ping_df[, .SD[c(1)], by = c("driver", "trip_id")]
# t2 = ping_df[, .SD[c(.N)], by = c("driver", "trip_id", "flag0")]
# trip_df = rbindlist(list(t1, t2), TRUE)
# setkey(trip_df, driver, ping_time)
# trip_df[,end_time := shift(ping_time, type = "lead", fill = NA), driver]
# trip_df = trip_df[!is.na(end_time), ]
# trip_df[, trip_id := .I]
# trip_df[, trip_time := as.integer(difftime(end_time, ping_time, 
#                                           units = "mins"))]
# trip_df = trip_df[, .(trip_id, driver, start_time = ping_time, end_time, trip_time, cum_mins)]
# setkey(trip_df, driver, start_time)
```

```{r}
# merge trip_id back to ping data
# setkey(trip_df, driver, start_time, end_time)
# ping_df[,dummy := ping_time]
# pitr_df = foverlaps(ping_df, trip_df,
#                     by.x = c("driver", "ping_time", "dummy"))[, dummy := NULL]
# pitr_df[,.(ping_id, driver, ping_time, trip_id, start_time, end_time, trip_time)]
```



