INTRODUCTION
============

Transportation safety
---------------------

Traffic safety \index{traffic safety} is a pressing public health issue that involves huge lives losses and financial burden across the world and in the United States (US). 
As reported by the World Health Organization [@who2018], road injury was the eighth cause of death globally in 2016, killing approximately 1.4 million people, which consisted of about 2.5% of all deaths in the world. 
If no sustained action is taken, road injuries are predicted to be the seventh leading cause of death across the world by 2030 [@who2018b]. 
Compared to the victims who were claimed lives by diseases, people killed in traffic are mostly   early- or middle-aged, particularly those aged 4 to 44 years old [@litman2013transportation; @evans2014traffic].
Without traffic accidents, these victims could have much longer lives with normal health.


Apart from fatal deaths, road traffic injuries were also reported to be the cause of 50 million non-fatal life injuries and approximately 75.5 million disability-adjusted life years globally [@staton2016road].
In high-income countries, the majority of non-death costs were attributable to non-fatal crashes, with 2% of non-fatal events leading to over 40% of life-time medical costs [@ameratunga2006road].
Besides non-fatal injuries, traffic safety is a major economic burden. 
The global economic losses attributable to transportation safety were estimated to be 518 billion the United States Dollars (USD), which accounted for 1% the gross domestic product (GDP) in low-income countries, 1.5% in middle-income countries, and 2% in high-income countries [@peden2004world; @dalal2013economics]. 


Specifically in the United States, transportation contributed to the highest number of fatal occupational injuries, leading to 2,077 deaths and accounting for over 40% of all fatal occupational injuries in 2017 [@bols]. 
The National Safety Council reported that the number of deaths attributable to car crashes will be at least 40,000 in 2018, which is the third straight year that this number is over 40,000 [@nsc2018]. 
A comparison study of 26 developed countries revealed that 20 to 60 traffic deaths per billion kilometers were reduced from 2011 [@evans2014traffic]. 
Even though fatality rates attributable to road traffic in the US were reduced by 40% during that period, the rates declined more rapidly in all other 25 countries.
Given the large amounts of investments in roads, improved vehicle protection and traffic policy implementation, and advanced emergency and trauma care, the reduction in traffic associated fatality rates is nominal [@litman2013transportation].
If the change of traffic fatality rates match those in other unremarkable countries, 20,000 traffic deaths could have been prevented each year [@evans2014traffic].

The impact of road injuries is even more impactful in developing countries than in developed countries [@goonewardene2010road].
Although low- and middle-income countries own only 48% of the registered vehicles in the world, 90% of road traffic fatalities and injuries were estimated to occur in these countries, which continue to be escalating due to rapid urbanization and motorization [@dalal2013economics; @staton2016road].
Ten developing countries, including Brazil, Cambodia, China, Egypt, India, Kenya, Mexico, Russia, Turkey, and Vietnam, account for almost half of all the road traffic in the world [@hyder2012addressing]. 
For example, China has around 100,000 traffic-related fatalities each year [@zhang2010road], accounting for around 80% of all accidental deaths, with 87% of them were caused by motor vehicles in 2015 [@jiang2017transport]. 
In comparison, 148,707 lives were claimed by road collisions in India in 2015, with the road fatality rate similar to the global average level of 17.4 deaths per 100,000 people [@india2015].





Trucking safety
---------------

In the US, the large commercial truck industry is the backbone of the economy. Approximately 70% of freight is delivered via a truck at some point of their transportation, which account for 73.1% of value and 71.3% of volume of the domestic goods [@olson2016weight; @anderson2017exploratory]. 
However, among all vehicles, large trucks are associated with more catastrophic accidents and therefore are the primary concern of traffic safety. In 2016, the Federal Motor Carrier Safety Administration (FMCSA) reported that 27% fatal crashes in work zones involved large trucks [@fmcsareport2016]. Among all 4,079 crashes involving large trucks or buses in 2016, 4,564 people (1.12 people per crash) were killed in the accidents [@fmcsafacts2016]. Large truck crashes approximately claim 5,000 lives and cause 120,000 injuries each year, but only 15% of these fatalities occur in the trucks, with a predominate 78% occurred in the other vehicles [@neeley2009effect]. Besides, the economic losses associated with large truck crashes are also higher than those with passenger vehicles, with an estimated average cost of 91,000 US dollars per crash [@zaloshnja2008unit]. 

The high risk of large trucks is attributed to two aspects of reasons [@huang2013development]. First, large truck drivers generally need to drive alone for long routes, under on-time demands, challenging weather and traffic conditions. Professional truck drivers usually need to work in shifts, and sometimes unavoidable late-night or early-morning shifts [@pylkkonen2015sleepiness]. These late-night or early-morning working shifts have been reported to be associated with sleep deprivation and disorders [@aakerstedt1988sleepiness; @mitler1997sleep; @solomon2004healthcare; @sallinen2005sleepiness]. Besides, commercial truck drivers are exposed to long route, constant concentration, and overtime work, which intertwines with sleep deprivation and disorder, and induce the fatigue symptoms among truck drivers.  It is estimated that fatigue among long distance truck drivers caused up to 31% of single vehicle fatal truck crashes [@ntsb1990; @mitler1997sleep]. 

On the other hand, trucks have huge weights, large physical dimensions, and potentially carry hazardous cargoes. Although these huge-size trucks boost the transportation efficiency by increasing cargo capacity and reducing fuel costs per trip, they also raise public safety concerns [@lemp2011analysis]. Large trucks can weight up to 80,000 pounds by federal law, which are twenty times as much as a passenger vehicle [@utah2019]. If these trucks travel at the speed of 65 miles per hour on the highway, it will take them 525 feet to stop, which is about two times the length of a football field [@utah2019]. The large physical size also creates large blind spots on both sides of the truck, which poses more threat on smaller-sized vehicles. When a crash occurs between a large truck and a smaller vehicle, the sheer size and weight of the truck result in the tragedy that the victims are from the smaller vehicle instead of the trucks in around 80% of the cases [@neeley2009effect]. In even worse case, commercial trucks crashes can cause massive casualties and regional public health emergency when the carried hazardous materials (such as gasoline and sulfuric acid) are leaked.


Crashes and critical events
---------------------------

To reduce the lives and economic losses associated with trucks, numerous studies attempted to screen the risk factors for truck-related traffic crashes or predict the crashes. The most common study design is a case-control study, matching a crash with one to up to ten non-crashes, and use statistical models such as logistic regressions to explain the causes or predict the crashes [@braver1997tractor; @chen2014modeling; @meuleners2015obstructive; @nee2019road]. This widespread case-control design is due to the fact that large truck crashes are very rare compared to the amount of time on road. However, a case-control study is limited in estimating the incidence data and may be contentious in selecting the control groups [@grimes2005compared; @sedgwick2014case]. 

Past truck safety literature almost exclusively focused on crashes, while ignoring the precursors to crashes. A precursor \index{precursor}, or critical event \index{critical event}, is a pattern or signature associated with an increasing chance of truck crash [@saleh2013accident; @janakiraman2016discovery]. Truck critical events deserve more attention since they occur more frequently than crashes, suggest fatigue and a lapse in performance, and they can lead to giant crashes [@dingus2006development]. Although critical events do not always result in an accident, they could be used as an early warning system to mitigate or prevent truck crashes [@kusano2012safety].


@de2018near

With modern technology, critical events are recorded more and more by truck companies. 


## Proposal

I propose using real-time truck ping data provided by the J.B. Hunt to


1) **quantify the association between truck crashes and critical events**;
2) **construct predictive models for truck critical events**;
3) **establish scalable Bayesian hierarchical models for large truck data**.


I believe that this work will contribute to statistical theories in constructing scalable Bayesian hierarchical statistical and reliability models using modern Markov Chain Monte Carlo methods. Realistically, these predictive models will inform policy-makers the functional relationship between driver characteristics, traffic, weather, and other real-time driving environment. These predictive models can be further used to provide data-driven justification to optimize trucking routes and minimize unsafe driving behaviors.