## Conceptual framework

@cantor2010driver suggested three factors that cause truck crashes: driver factors, vehicle factors (type and condition), and environmental factors.

@roshandel2015impact proposed five factors that affect traffic safety: (a)  behavioral characteristics of the driver, e.g., impairment, fatigue, distractions; (b) vehicle --- the condition of the vehicle; (c) traffic --- the traffic conditions; (d) geometry --- geometric characteristics of the road, e.g. curve, hill, ramps, etc.; and (e) environmental --- characteristics of the surrounding environment, such as weather conditions (rain, snow, night-time driving, etc.). Traffic conditions are the most studied of these and we focus on discussing them in this subsection.




## Gaps in literature

- A focus on crashes instead of precursors of crashes
- A focus on road segments rather than drivers
- A focus on case-control comparison given the rareness of truck crashes rather than rates

## Research aims

**Aim1**: 



**Aim2**: 



**Aim3**: 


