METHODS
=======

Data source
-----------

### Real-time ping

The J.B. Hunt Transport Services, a trucking and transportation company in the United States,
provided real-time ping data on 496 truck drivers who conducted regional work (REG, JBI00) from April 1st, 2015 to March 29th, 2016 to the research team. 
A small device was installed in each of their truck, which will ping irregularly (typically every 5-30 minutes). 
Each **ping** will collect real-time data on the vehicle number, date and time, latitude, longitude, driver identity number, and speed at that second. 
In total, 13,187,289 pings were collected and provided to the research team. 


For each of the truck drivers, if the ping data showed that the truck was not moving for more than 20 minutes, the ping data were separated into two different trips. 
These ping data were then aggregated into different trips. 
A **trip** is therefore defined as a continuous period of driving without stop. 
The average length of a trip in this study is 2.31 hours with the standard deviation of 1.8 hours.

After the ping data were aggregated into trips, these trips data were then further divded into different shifts according to an eight-hour rest time for each driver. 
A **shift** is defined as a long period of driving with potentially less than 8 hours' stops. 
The Shift_ID column in Table \@ref(tab:tripsdata) shows different shifts, separated by an eight-hour threshold. 
The average length of a shift in this study is 8.42 hours with the standard deviation of 2.45 hours.

### Truck crashes and critical events



The company regularly collected real-time GPS location and time-stamped critical events data for all their trucks. 
Four types of critical events were recorded in the critical events data:

1.	Hard brake
2.	Headway
3.	Rolling stability
4.	Collision mitigation

Once some thresholds with regard to the driver's operation were met, the sensor will be triggered and critical events will be recorded in their database.
There were 12,458 critical events created by the 496 truck drivers during the study period. 

### Driver demographics

These variables can be linked to the trips and crashes table via a common unique identifier.

### Weather data from the `DarkSky API`

We retrieved weather variables from the Dark Sky API: *precipitation intensity*, *precipitation probability*, *wind speed*, and *visibility*. 
The DarkSky API allows the users to query historic minute-by-minute weather data anywhere on the globe [@darksky]. 
According to the official document, the Dark Sky API is supported by a wide range of weather data sources, which are aggregated together to provide the most precise weather data possible for a given location [@darkskyds]. 
Among several different weather data providers we tested, the Dark Sky API provides the most accurate and complete weather variables.

To reduce the cost of querying weather data for the 13 million historic ping data, we rounded the latitudes and longitudes coordinates to two decimal places, which were worth up to 1.1 kilometers 
We also rounded the time to the nearest hour and ignore those stopping pings. 
This scaled the original 13 million ping data down to 4.9 million unique latitude-longitude-date-time combinations. 
We used the R package `darksky` to obtain weather variables for these reduced 4.9 million unique  combinations [@hrbrmstr]. 
The weather data for these combinations were then merged back to the origin data.
A minimal example of R code to retrieve weather data from the DarkSky API can be found in Appendix \@ref(weatherdat).

### Road geometry data from the `OpenStreetMap`

We queried two road geometry variables from the `OpenStreetMap` (OSM) project: *speed limit* and *the number of lanes*. 
The OSM data are collaboratively collected by over two million registered users via manual survey, GPS devices, aerial photography, and other open-access sources [@wikiOSM]. 
The OpenStreetMap Foundation supports a website to make the data freely available to the public under the Open Database License. 

We queried the speed limit and the number of lanes by specifying a bounding box by defining a center point, as well as the width and height in meters in the `center_bbox()` function available from the `osmar` R package [@eugster2013osmar]. 
We used real-time longitudes and latitudes as the center point and defined a $100\times100$ meters box to retrieve the two variables. 
If the $100\times100$ meters box is too small to have any road geometry data, we expanded the box to $500\times500$ and then $1000\times1000$ to obtain geometry data. 
If the OSM API returned data from multiple geometry structures, we took the mean as the returned values. 
The R code to retrieve road geometry data can be found in Appendix \@ref(roadgeometry).

















