Analytical Plan for Aim 2
-------------------------



In this study, we use vehicle drivers as the sampling unit and adopt hierarchical statistical models that accounts for both driver-level variation and trip-level variation. The workflow is to sample a certain number of drivers from a population of drivers, observe their driving trips or shifts for a specific period, then compare the safety events with non-events, and make conclusions on risk factors associated with these safety events.

### Logistic regression

Here we model the probability of a critical event occurred using a Bayesian hierarchical Bernoulli regression. We categorize the number of safety events during a trip into a binary variable $Y$ of either 0 or 1, where 0 indicates that no critical event occurred during that trip while 1 indicates that at least 1 critical event occurred during the trip. Since each trip $i$ has a different travel time $t_i$, we derived the Bernoulli distribution parameter $p_i$ using a Poisson distribution, with the parameter $\lambda_i$ represented by a linear combination of $\beta_i$\ and $x_i$.

$$
\begin{split}
Y_{i, d} &\sim \text{Bernoulli}(p_i)\\
\log\frac{p_{i, d}}{1-p_{i, d}} &= \beta_{0, d(i)} + \beta_{1, d(i)} \cdot \text{CT}_i + \mathbf{\xi} \cdot \mathbf{W} + \mathbf{\nu} \cdot \mathbf{D_i}\\
\beta_{0, d} &\sim N(\mu_0, \sigma_0^2), \quad k = 1, 2, \cdots, D
(\#eq:hierarchicallogit)
\end{split}
$$

Here the trip is indexed by $i$, $Y_i$ is the binary outcome variable of whether at least one critical event occurred in trip $i$; $d(i)$ is the driver for trip $i$, $\beta_{0, d(i)}$ is the random intercept for driver $d(i)$; $\beta_{1, d(i)}$ is the random slope for the cumulative time (CT$i$) of driving in the shift (the sum of driving time for all previous trips) for driver $d(i)$; $\mathbf{W}$ is a vector of external environment fixed effects, including precipitation intensity and probability, visibility, and whether it was sunrise or sunset time; $\mathbf{D}_i$ are driver level fixed effects, including age group and business unit; $t_i$ is the travel time for the trip $i$.

We assume that the drivers are random effects, and we assume exchangeable priors of the form
\[
\beta_{0, d(1)}, \beta_{0, d(2)}, \ldots , \beta_{0, d(n)} \sim \text{i.i.d.} N(\mu_0,\sigma_0^2)
\]
and 
\[
\beta_{1, d(1)}, \beta_{1, d(2)}, \ldots , \beta_{1, d(n)} \sim \text{i.i.d.} N(\mu_1,\sigma_1^2)
\]
The parameters $\mu_0, \sigma_0, \mu_1$, and $\sigma_1$ are hyperparameters with priors. Since we do not have much prior knowledge on the hyperparameters, we assigned diffuse priors for these hyperparameters.
\begin{align}
	\label{prior}
	\begin{split}
		\mu_0 & \sim N(0, 10^2)\\
		\mu_1 & \sim N(0, 10^2)\\
		\sigma_0 & \sim \text{GAMMA}(1, 1)\\
		\sigma_1 & \sim \text{GAMMA}(1, 1)
	\end{split}
\end{align}
Since $\mu_0$ and $\mu_1$ can be any real number, so we assigned two normal distributions with mean of 0 and standard deviation of 10 as the priors for these two hyperparameters. In comparison, $\sigma_0$ and $\sigma_1$ must be strictly positive, so we assigned GAMMA$(1, 1)$ with wide distribution on positive real numbers as their priors.

### Poisson regression

Since logistic regression ignores the intensity of the critical events with any number greater than 0 categorized into 1, I adopt a Bayesian hierarchical Poisson regression to model the effect of cumulative driving time on the occurrence of critical events. Each driver has a random intercept and a random slope on cumulative driving time.
\begin{align}
\label{pois}
\begin{split}
\text{N} & \sim \text{POIS}(t\cdot\lambda)\\
\lambda_{d(i)} & =\exp(\beta_{0, d(i)} + \beta_{1, d(i)} \cdot \text{CT} + \mathbf{\xi} \cdot \mathbf{W} + \mathbf{\nu} \cdot \mathbf{D})
\end{split}
\end{align}
Where N is the number of critical events for driver $d(i)$ in time interval $j$, and it has a Poisson distribution with parameter $\lambda$. The other variables are identical as those described in Equation .

**Censored Poisson Regression**

In real data, some trips have over 40 critical events and these values cannot be true, so we assume these data points are censored at 5, which means any trips with more than 5 critical events are not observed, but we do know that these unobserved values are more than 5.

For those trips with less than 5 critical events, we still assume the number of critical events has a Poisson distribution. However, we assume the number of critical events of trips with over 5 critical events are right censored at 5. We can integrate out these censored values by:

\begin{align*}
Pr(Y > 5) & = 1 - Pr(Y \leq 5)\\
& = 1 - \sum_{i=0}^5\Lambda(t\cdot\lambda)
\end{align*}
Where $\Lambda$ is the Poisson cumulative distribution function.

The log joint density function is then:

\begin{align*}
\log\prod_{i=1}^nPr(Y_i > 5) & = \log\Big(1 - \sum_{i=0}^5\Lambda(t\cdot\lambda)\Big)^n\\
& = n\log\Big(1 - \sum_{i=0}^5\Lambda(t\cdot\lambda)\Big)
\end{align*}

This can be straightforwardly evaluated in `Stan` using the `poisson_lccdf` function.

### Non-homogeneous Poisson process

**Mean function of a point process**: 

$$\Lambda(t) = E(N(t))$$

$\Lambda(t)$ is the expected number of failures through time $t$.

**Rate of Occurence of Failures (ROCOF)**: When $\Lambda$ is differentiable, the ROCOF is:

$$\mu(t) = \frac{d}{dt}\Lambda(t)$$
The ROCOF can be interpreted as the instantaneous rate of change in the expected number of failures.

**Intensity function**: The intensity function of a point process is 

$$\lambda(t) = \lim_{\Delta t \rightarrow 0}\frac{P(N(t, t+\Delta t] \geq 1)}{\Delta t}$$

When there is no simultaneous events, ROCOF is the same as intensity function.


**Nonhomogeneous Poisson Process (NHPP)**: The NHPP is a Poisson process whose intensity function is non-constant.

**Power law process (PLP)**: When the intensity function of a NHPP is:

$$\lambda(t) = \frac{\beta}{\theta}\bigg(\frac{t}{\theta}\bigg)^{\beta-1}$$

Where $\beta > 0$ and $\theta > 0$, the process is called the power law process (PLP).

Therefore, the mean function $\Lambda(t)$ is the integral of the intensity function:

$$\Lambda(t) = \int_0^t \lambda(t)dt = \int_0^t \frac{\beta}{\theta}\bigg(\frac{t}{\theta}\bigg)^{\beta-1} = \bigg(\frac{t}{\theta}\bigg)^{\beta}$$

There are two forms of truncation in a NHPP:

1. **Failure truncation**: When testing stops after a predetermined number of failures, the data are said to be failure truncated.
2. **Time truncation**: Data are said to be time truncated when testing stops at a predetermined time $t$.

In a time truncated case, the joint likelihood function for $f(n, t_1, t_2, \cdots, t_n)$ is (the prove can be found in the Appendix):
\begin{equation}\label{pdftau}
\begin{aligned}
f(n, t_1, t_2, \cdots, t_n) & = f(n)f(t_1, t_2, \cdots, t_n|n)\\
& = \frac{e^{-\int_0^\tau \lambda(u)du}[\int_0^\tau \lambda(u)du]^n}{n!}n!\frac{\prod_{i=1}^n\lambda(t_i)}{[\Lambda(\tau)]^n}\\
& = \Big(\prod_{i=1}^n\lambda(t_i) \Big)e^{-\int_0^\tau \lambda(u)du}\\
& = \Big(\prod_{i=1}^n\frac{\beta}{\theta}(\frac{t_i}{\theta})^{\beta - 1} \Big)e^{-(\tau/\theta)^\beta},\\ 
n & = 0, 1, 2, \cdots, \quad  0 < t_1 < t_2 < \cdots < t_n
\end{aligned}
\end{equation}

The log likelihood function $l$ is then:
\begin{equation}\label{logtau}
\begin{aligned}
l & = \log \Bigg(\Big(\prod_{i=1}^n\frac{\beta}{\theta}(\frac{t_i}{\theta})^{\beta - 1}\Big)e^{-(\tau/\theta)^\beta}\Bigg)\\
& = \sum_{i=1}^n\log\Big(\frac{\beta}{\theta}(\frac{t_i}{\theta})^{\beta - 1}\Big) - (\frac{\tau}{\theta})^\beta\\
& = n\log\beta - n\beta\log\theta + (\beta - 1)\bigg(\sum_{i=1}^n\log t_i\bigg) - \Big(\frac{\tau}{\theta}\Big)^\beta
\end{aligned}
\end{equation}
