# THE PROBABLE CONTENT

The contents will follow the standard format for a traditional dissertation, as per guidelines set by the College for Public Health and Social Justice and Saint Louis University’s Office of Graduate Education.

\singlespacing

* Chapter 1: Introduction: The problem
    1. Transportation safety
    2. Truck safety
    3. Modern truck safety studies
* Chapter 2: Literature review
    1. Naturalistic driving Study (NDS)
    2. Safety-critical events (SCEs)
    3. Crashes and SCEs
    4. Risk factors for traffic safety
    5. Predictive models: 
        a. Bayesian models, 
        b. Hierarchical models, 
        c. Markov chain Monte Carlo (MCMC)
    6. Scalable Bayesian models: 
        a. Hamiltonian Monte Carlo (HMC), 
        b. Subsampling MCMC
* Chapter 3: Aim 1 - Truck crashes and SCEs
    1. Introduction
    2. Data sources and methods
    4. Results
        a. A simulation study on Gamma-Poisson models
        b. Real-world application on all SCEs
        c. Real-world application on different types of SCEs
    5. Discussion  
* Chapter 4: Aim 2 - Scalable Bayesian hierarchical models for SCEs using HMC-ECS
    1. Introduction
    2. Data and methods
    3. Results
        a. Bayesian hierarchical logistic regression
        b. Bayesian hierarchical Poisson regression
        c. Bayesian hierarchical Non-homogeneous Poisson process (NHPP)
    4. Discussion
* Chapter 5: Aim 3 - a JPLP that accounts for between trip rest time
    1. Introduction
    2. Data sources and methods
    4. Results
        a. A simulation study on this new method
        b. Real-world application on this new method
    5. Discussion
